### ISSUE TITLE
[4.1/dnsauth] error: cast from pointer to smaller type 'char' loses information on dnsauth

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#221]
error: cast from pointer to smaller type 'char' loses information while trying to compile dnsauth

ConnectionHandler.cpp:4594:24: error: cast from pointer to smaller type 'char' loses information
                p[j] = (char)NULL;
                       ^~~~~~~~~~

**Comment by marcelloc** [comment]
Does p[j] = '\0'; looks a workaround or fix for it?  

If so, it needs to be applied on authplugins/dnsauth.cpp:264:24 too
 error: cast from pointer to smaller type 'char' loses information
                p[j] = (char)NULL;

**Comment by fredbcode** [comment]
Yes I guess, as is an array that store elements of type char 

p[j] = "";  

Should be better
I will discuss with Philip, maybe there is a reason I don't see

**Comment by fredbcode** [comment]
Oups sorry, of course you are right 

No related we are working on 4.1.1 there are several fixes 
You can make a try, with branch 'retryfix'

**Comment by marcelloc** [comment]
what is the current branch to test fixes? looks like retryfix is back to 3.5.1

**Comment by fredbcode** [comment]
retryfix 

Le 31 mai 2017 22:11:41 GMT+02:00, Marcello Coutinho <notifications@github.com> a écrit :
>what is the current branch to test fixes? looks like retryfix is back
>to 3.5.1
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/221#issuecomment-305302766

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
